### ISSUE TITLE
Optimized for speed Segment 32050: Signal Edge Detector (now 243, was 286)

### ISSUE THREAD

**Issue by gmnenad** [kk4ead/tis-100#28]
Node @1 is calculating difference to previous inputs, and use @0 and @2 to save previous values.
Node @5 is passing difference to @6 if positive, or @8 if negative ... and they decide if difference is above 10.  
Noce @9 will get result from either positive or negative node, so it uses ANY.

'@0
MOV ACC,RIGHT
MOV RIGHT,ACC

@1
MOV UP,ACC
MOV ACC,RIGHT
SUB LEFT
MOV ACC,DOWN

MOV UP,ACC
MOV ACC,LEFT
SUB RIGHT
MOV ACC,DOWN

@2
MOV LEFT,LEFT

@3

@4

@5
START:
MOV UP,ACC
JLZ END
MOV ACC,RIGHT
JMP START
END:
MOV ACC,DOWN

@6
START:
MOV LEFT,ACC
SUB 10
JLZ END
MOV 1,DOWN
JMP START
END:
MOV 0,DOWN

@7

@8
START:
MOV UP,ACC
ADD 10
JGZ END
MOV 1,RIGHT
JMP START
END:
MOV 0,RIGHT

@9
MOV ANY,DOWN

@10'

**Comment by kk4ead** [comment]
Current speed-optimized solution has 218 cycles
