### ISSUE TITLE
optimize Signal Multiplier for speed

### ISSUE THREAD

**Issue by kk4ead** [kk4ead/tis-100#9]
The attached program uses shift-and-add multiplication, but is slow; determine if it can be made faster than the solution given in chapter 5.

[43786.1.txt](https://github.com/kk4ead/tis-100/files/52764/43786.1.txt)

**Comment by CaitSith2** [comment]
Faster than the chapter 5 solution, using shift and add. :)
[Shift & Add](https://github.com/kk4ead/tis-100/files/53480/43786.1.txt) 789 cyles, 5 nodes, 46 instructions
[Speed Optimized](https://github.com/kk4ead/tis-100/files/53482/43786.2.txt) - 474 cycles, 6 nodes, 46 instructions
[Size Optimized](https://github.com/kk4ead/tis-100/files/53483/43786.0.txt) - 639 cycles, 4 nodes, 31 instructions

The smaller number check is actually slower in the size optimized version.
